POST http://localhost:8086/api/authorizations
Content-Type: application/json
Accept: application/json

{
  "cardId": 1,
  "amountCent": 1500
}
###


GET http://localhost:8086/api/authorizations/1
Accept: application/json

###
GET http://localhost:8086/api/authorizations
Accept: application/json


###

DELETE http://localhost:8086/api/authorizations/1
Accept: application/json



###

GET http://localhost:8086/api/authorizations/card/1
Accept: application/json

###
PATCH http://localhost:8086/api/authorizations/1/status?status=AUTHORIZED
Accept: application/json



