POST  http://localhost:8086/api/cards
accept: application/json
Content-Type: application/json

{
  "accountId": 1,
  "pan": "1234567890987654",
  "cvv": "123",
  "expiryDate": "2027-12"
}





###
GET http://localhost:8086/api/cards
accept: application/json


###


GET http://localhost:8086/api/cards/1
Accept: application/json


###

DELETE http://localhost:8086/api/cards/1
accept: application/json

###

PATCH http://localhost:8086/api/cards/1/inactive
accept: application/json


###

PATCH http://localhost:8086/api/cards/1/block
accept: application/json