### Загрузка аватара
POST http://localhost:8080/api/user-avatars/1
Content-Type: multipart/form-data; boundary=WebAppBoundary
Accept: application/json

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="sunny.jpg"
Content-Type: image/jpeg

< /home/ilgiz/Pictures/Walpaper/15453785-19dd2483-2973-4128-931d-56d292fc120d.jpg
--WebAppBoundary--

###


### Получение информации об аватаре (если добавите эндпоинт)
GET http://localhost:8080/api/user-avatars/1
Accept: application/json
Accept: image/jpeg, image/png, image/gif, image/webp
###



### Скачивание файла аватара (если добавите эндпоинт)
GET http://localhost:8080/api/user-avatars/1/download
Accept: image/jpeg, image/png, image/gif, image/webp

###