### Создать профиль пользователя
POST http://localhost:8080/api/user-profiles
accept: application/json
Content-Type: application/json

{
  "firstName": "Ilgiz",
  "lastName": "Samudinov",
  "userId": 2
}

###

### Получить все профили
GET http://localhost:8080/api/user-profiles
accept: application/json

###

### Получить профиль по ID
GET http://localhost:8080/api/user-profiles/1
accept: application/json

###

### Обновить профиль пользователя
PUT http://localhost:8080/api/user-profiles/1
accept: application/json
Content-Type: application/json

{
  "firstName": "IlgizUpdated",
  "lastName": "RugizovUpdated",
  "userId": 1
}

###

### Удалить профиль пользователя
DELETE http://localhost:8080/api/user-profiles/1
accept: application/json
