### Создать новую резервацию
POST http://localhost:8085/api/inventory-reservations
Content-Type: application/json
Accept: application/json

{
  "inventoryId": 1,
  "orderId": 1,
  "quantity": 50
}



### Получить все резервации
GET http://localhost:8085/api/inventory-reservations
Accept: application/json

###

### Получить резервацию по ID
GET http://localhost:8085/api/inventory-reservations/1
Accept: application/json

###


###

### Обновить резервацию
PUT http://localhost:8085/api/inventory-reservations/1
Content-Type: application/json
Accept: application/json

{
  "inventoryId": 1,
  "orderId": 10,
  "quantity": 70,
  "reservationStatus": "CONFIRMED"
}

###

### Удалить резервацию
DELETE http://localhost:8085/api/inventory-reservations/1
Accept: application/json

###

### Подтвердить (consume) резервацию
POST http://localhost:8085/api/inventory-reservations/3/consume
Accept: application/json

###

### Освободить (release) резервацию
POST http://localhost:8085/api/inventory-reservations/3/release
Accept: application/json

###

### Истечь (expire) резервацию
POST http://localhost:8085/api/inventory-reservations/1/expire
Accept: application/json
